### ISSUE TITLE
Missing "Route to" and other buttons

### ISSUE THREAD

**Issue by kuba-orlik** [organicmaps/organicmaps#1021]
Sometimes the app enters in a state where opening any POI pop-up doesn't show the regular buttons ("route to", "route from", "bookmark", etc).

![photo_2021-08-06_15-07-57](https://user-images.githubusercontent.com/2697916/128514937-914ea6b9-18b8-4f8f-b5ea-e67bea77ca50.jpg)

Only after force closing the app the buttons start to appear, but it doesn't take long for this bug to reoccur.

**Comment by biodranik** [comment]
This layout bug should be fixed in the latest upcoming update.

**Comment by rtsisyk** [comment]
This update is live. Please re-open if problem still exists.

**Comment by kuba-orlik** [comment]
The issue still occurs for me on version 2021.08.05

![photo_2021-08-16_12-06-44](https://user-images.githubusercontent.com/2697916/129547493-afe020f0-5339-4360-b041-8b7a67c1c3fd.jpg)

**Comment by bbinet** [comment]
Same issue here.

**Comment by kuba-orlik** [comment]
I can reproduce it with 100% accuracy with these steps:

1. Force close the app
2. Open the app
3. Go straight to search
4. Enter some text
5. Pick a search result

My workaround is to tap anything on the map first before going to search. Then the issue does not occur.

**Comment by biodranik** [comment]
@kuba-orlik is it Android 11?

**Comment by kuba-orlik** [comment]
That's right, Android 11

**Comment by biodranik** [comment]
Bottom menu does not appear when I switch to other app and after maps restarting.

 ![image](https://user-images.githubusercontent.com/170263/136551629-d90852ff-5763-41a5-bc96-4eb8d2c302d7.jpeg)

**Comment by biodranik** [comment]
It always happen on Android 11

![image](https://user-images.githubusercontent.com/170263/136552678-0aaa2642-9195-40cc-8101-4d24121ec0b8.jpeg)
