### ISSUE TITLE
Save track button is disabled when building a route

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#11043]
1. Build a route.
2. Press Save button.
3. Press Delete (track) button.
4. Observe route planning screen with disabled Save button.

CC @kirylkaveryn @kavikhalique

**Comment by kirylkaveryn** [comment]
There is the same issue

https://github.com/organicmaps/organicmaps/issues/10747

It is fixed in a new routing in iOS.

**Comment by biodranik** [comment]
@kirylkaveryn I forgot to mention that I discovered it in the latest beta.

**Comment by zloidemon** [comment]
[Alexander Borsuk](https://github.com/biodranik) How can this bugs still slip through if you rigorously review every PR and require approvals before merging?

**Comment by kirylkaveryn** [comment]
> @kirylkaveryn I forgot to mention that I discovered it in the latest beta.

The save button should be active after saving only when:
1. The stops array are not equal (eg if you are walking and the coordinates of current location stop is changed)
2. The transport option is changed (bike pedestrian etc)
3. The screen is recreated

Can you please share the screen _recording_ when the button is active after deletion so I can reproduce the issue? And can you confirm that the location wasn't changed (the route wasn't rebuild)?

https://github.com/user-attachments/assets/121e6a9e-1dad-4c8f-be41-e182b28e291d
