### ISSUE TITLE
[android] POI's Wikipedia summary disappears after bookmarking

### ISSUE THREAD

**Issue by pastk** [organicmaps/organicmaps#2825]
1. Tap a POI that has an attached Wikipedia article.
2. Open the bottom info sheet.
3. There will be a Wiki article preview shown.
4. Bookmark this POI.
5. The Wiki preview is not available in the bottom info sheet anymore and it seems like its no way to display the article unless a bookmark is removed.
(the Wikipedia link is visible though).

**Comment by vbertola** [comment]
This is a common and noticeable bug, and quite annoying too.

**Comment by arnaudvergnet** [comment]
Fixed by https://github.com/organicmaps/organicmaps/pull/4174

**Comment by Jean-BaptisteC** [comment]
Not fixed on city or airplane on regions not downloaded

**Steps to reproduce**
1. Select on map city or airplane on regions not downloaded
2. Expand place page -> website, wikipedia, wikimedia links are present
3. Click on save -> POI is save in list
4. Links in place page are missing

**Comment by biodranik** [comment]
Did it work before? @vng WDYT?
