### ISSUE TITLE
Support geo:0,0?q=my+street+address links used in many Calendar apps

### ISSUE THREAD

**Issue by jimcarst** [organicmaps/organicmaps#320]
Hi!

On Android, when selecting text that contains an address, next to 'cut' and 'copy', there is a 'map' button. It should take you directly to the location in a map app. This seems to be a handy link. Android lets me choose between Google Maps and Organic Maps. When I choose the former, the location appears, but when I choose the latter, it opens and nothing else happens.

It would be nice to allow Organic Maps to accept this shortcut.

Cheers!

**Comment by biodranik** [comment]
Looks like it's about [geo:// url scheme](https://en.wikipedia.org/wiki/Geo_URI_scheme) (NOT ge0!).

This [link](geo:0,0?z=14&q=54.683486138,25.289361259) should work on all platforms.

**Comment by rtsisyk** [comment]
This problem has been fixed a month of two again. Please update to the latest version.

**Comment by biodranik** [comment]
@rtsisyk no, it's a different issue. Contacts app uses a different scheme, probably geo://. We need to recheck and fix it properly if necessary. @jimcarst can you please confirm that it still doesn't work for you?

**Comment by jimcarst** [comment]
Indeed, it still does not work on the most recent Google Play version of the app.

**Comment by biodranik** [comment]
We should add parsing of the following URI:
`geo:0,0?q=STREETNUMBER%20HOUSENUMBER%0ACITY%2C%20STATE%20ZIPCODE%0ACOUNTRY`

**Comment by Inrumpo** [comment]
#1020 brought me here.
I'm using Organic Maps on a Pixel 4a with CalyxOS 2.9.0 (Android 11). Clicking an address in the default (stock Android?) Contacts app allows me to open that link in Organic Maps or my Browser. Opening it in Organic Maps does open the app but nothing happens afterwards (as described in #1020). Opening that link in my browser does reveal a link like this:
`https://www.google.com/maps/dir//STREET+HOUSENUMBER+ZIPCODE+CITY/@NUMBER,NUMBER,NUMBERz/data=!` followed by a lot of cryptic values I have no clue what they could be about.

I'd rather have Organic Maps handle those links instead of Googel Maps in my mobile browser.

**Comment by rtsisyk** [comment]
Yes, this is a know bug. No only on Calyx. ---- On Mon, 20 Sep 2021 16:06:54 +0300  ***@***.***  wrote ----
#1020 brought me here.
I'm using Organic Maps on a Pixel 4a with CalyxOS 2.9.0 (Android 11). Clicking an address in the default (stock Android?) Contacts app allows me to open that link in Organic Maps or my Browser. Opening it in Organic Maps does open the app but nothing happens afterwards (as described in #1020). Opening that link in my browser does reveal a link like this:
***@***.***,NUMBER,NUMBERz/data=! followed by a lot of cryptic values I have no clue what they could be about.
I'd rather have Organic Maps handle those links instead of Googel Maps in my mobile browser.

**Comment by rtsisyk** [comment]
This format is needed for Instagram.

**Comment by christf** [comment]
#1361 brought me here. this time from the contacts app.

**Comment by biodranik** [comment]
The simplest fix could be converting the source url to our search api url mentioned here: https://omaps.app/api
