### ISSUE TITLE
Valid name with an apostrophe not found

### ISSUE THREAD

**Issue by richlv** [organicmaps/organicmaps#3420]
Searched for "Ben's Fish and Chips" while in London, found nothing.
Was sure it's not mapped, until I walked to it and attempted to map it...

Turns out, it is only found if I search for "Bens Fish and Chips", omitting the apostrophe.

Issue #1262 handled something similar recently, and some changes were merged on August 11th in #3128, but this behaviour was observed with Organic Maps 2022.08.23-3.

Object in OSM: https://www.openstreetmap.org/node/5009891423 .

**Comment by richlv** [comment]
Same with 2022.09.15-2 .
The first result for "ben’s fish and chips" is "South Park".

**Comment by Jean-BaptisteC** [comment]
Fixed in 2024.01.09-6-Google

**Comment by richlv** [comment]
Hi, what is that name, is "-Google" somehow related?
Was it supposed to be a link to a commit or such?

**Comment by biodranik** [comment]
@richlv do you still reproduce the issue on the latest January Organic Maps version?

**Comment by richlv** [comment]
Haven't tried it, don't want to download extra maps right now :)
Curious about the mentioned name - if that is a version number, why is there "-Google"?
For example, was this fixed for Android only?

**Comment by Jean-BaptisteC** [comment]
Google is the type of version app:
- Google version include library to use Google Play Services location
- Fdroid version doesn't include this library
Correction is fixed on IOS and Android, this code is shared between all platforms

**Comment by richlv** [comment]
Heya, thanks - still not sure how "-Google" came into play here, but glad to hear it's supposed to be working OK in all platforms now :)

**Comment by Jean-BaptisteC** [comment]
Because, I have tested on this version :)
