### ISSUE TITLE
[android] Subway panel covers controls 

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#3532]
Controls should move up when panel size increases.

![image](https://user-images.githubusercontent.com/170263/193701717-7469a5c6-ecfd-42a0-ba69-49dd22f10054.png)

However, there's also another issue: if you select any object on the map when the panel is visible, the panel will be covered by Place Page with action buttons in a bit ugly way (especially in the dark mode). I don't have any ideal solutions here in mind. Moving the panel to the top? But then it won't be easy to start navigation if the "Start" button also moves up.

Any ideas?

**Comment by arnaudvergnet** [comment]
I would put all the content inside a bottom sheet the user can expand when there is too much information, much like the place page. We could also move the top bar at the bottom in the same way the place page has action buttons at the bottom. So essentially move all the controls at the bottom and leave the map with the route at the top.

When showing the place page, we could hide the navigation menu so it won't overlap with it. This only issue I have is that there would not be any indication that we are still in routing mode when selecting an object in the map.

**Comment by biodranik** [comment]
1. Putting everything into a bottom sheet doesn't look right, considering that the user needs to constantly select points on the map to add stops.
2. Moving the top bar to the bottom doesn't look right for the same reason (the current mode will be hidden by the place page, or will hide? when the bottom sheet is closed).
3. A better solution probably would be to move this route info panel up, to the top. Then it will be always visible and convenient to use.
4. For landscape, we should brainstorm on how to show the map together with all panels and buttons. Maybe something like this?
```
[info panel][routing mode buttons]

                               [+]
[p]                            [-]
[*]                            [o]
         [   place page    ]
```

**Comment by rtsisyk** [comment]
Yes, it does cover if you have very complex route with 5 stopovers, like on the picture. But it is hard to imagine such situation even in Tokyo, London, or Moscow. Probably this particular issue is not a big deal, isn't it?

**Comment by biodranik** [comment]
Ok, it is not a blocker for the release. But of course, the usability should be fixed.

**Comment by Jean-BaptisteC** [comment]
This problem is partially fixed, but open/close place page in front of the routing plan, update the position of floating buttons, and go back to the main issue
