### ISSUE TITLE
[routing] Very strict penalties for unpaved grade road.

### ISSUE THREAD

**Issue by vng** [organicmaps/organicmaps#3716]
The app makes a 20km detour here: https://www.openstreetmap.org/directions?engine=graphhopper_car&route=41.54516%2C1.79168%3B41.55036%2C1.78887#map=17/41.54796/1.79151

**Comment by Jean-BaptisteC** [comment]
Fixed in 2023.11.17-18-Google

**Comment by tonikny** [comment]
I provided this info and it was closed as resolved, but the problem persists.

You can see it in the same example above. It's an unpaved track, surface: gravel, track type: grade2 and OM gives me 11min by car, 8min by foot and 3min by bicycle for 660m. I supose the tagging is fine, but by car you can drive about 40km/h there.

Maybe the issue can be reopened? Thanks.

**Comment by Jean-BaptisteC** [comment]
Can you give more details about the route?

**Comment by tonikny** [comment]
What kind of details do you need? I think it's a very common unpaved track, but is used frequently because shorts the way between parts of the same municipality and is maintained regularly.

**Comment by Jean-BaptisteC** [comment]
CC @vng
