### ISSUE TITLE
Voice navigation/routing instructions are not working in background/sleep mode

### ISSUE THREAD

**Issue by G-i-o** [organicmaps/organicmaps#573]
Using on Lineage 17.1 based on Android 10.

When the phone locks and goes into sleeping mode, the voice disappear. I've noticed this on OM v2021.05.21 and it's still present on v2021.06.07

**Comment by biodranik** [comment]
Did the voice work while locked in older versions?

**Comment by G-i-o** [comment]
I discovered OM on F-Droid where it started
appearing from v2021.05.21

On Sat, 2021-06-12 at 23:16 -0700, Alexander
Borsuk wrote:

**Comment by tangsgod** [comment]
Hi G-i-o, I'm also using on Lineage 17.1 based on Android 10, mine is on a redmi note 8, but I can't get the voice working. Did you install MicroG ?

**Comment by G-i-o** [comment]
Hi Tangsgod. No, I don't use Google services so my
Lineage installation was the bare one. All other
apps that have voice/sound/music running during
the lock state work except one (Breath). On this
the developer has already admitted that the app
need updating to something Android have changed in
the recent years and he's not sure how to do it.

He mentioned that the problem to overcome occurs
when the sounds to be played are not a sequence
like a in a playlist. So, i speculate that the
problem could be the same as on OM.

**Comment by rtsisyk** [comment]
Navigation in background mode is not yet implemented on Android.

**Comment by G-i-o** [comment]
It works for OsmAnd and OpenTracks.

**Comment by Turbotomate** [comment]
I really thin this is an important feature! I still have to use Google Maps all the time because there is no navigation possible with OM for my needs. Most of the people i know use navigation with the screen turned off aswell.
Can we put together some things that have to be done, some things that are already finished and maybe a rough ETA?

**Comment by Tc-001** [comment]
For the app https://github.com/kylecorry31/Trail-Sense, there is the option to allow location "all the time", we may need to add that for this to work.

![Screenshot_20220412-105911_1_1](https://user-images.githubusercontent.com/55956895/162911500-61ab7d9f-dd00-402c-9e44-bb6ed0066535.png)

From a quick looks you would probably need the `android.permission.ACCESS_BACKGROUND_LOCATION` (https://github.com/kylecorry31/Trail-Sense/blob/055bc88fc849adee70b4a453804449dcdcc8dd09/app/src/main/AndroidManifest.xml#L15) premission for this to work, that I don't see requested in https://github.com/organicmaps/organicmaps/blob/fdf632e213b88219411705fff775311a4e2c0c6d/android/AndroidManifest.xml

May be 100% wrong, so feel free to correct me

**Comment by towolf** [comment]
I was messing around a lot with the ancestor app and this one trying to get navigation to work when the phone is in my pocket. Seems like the background permission would be all that's needed?

**Comment by biodranik** [comment]
No, the background service should be user-visible to keep it always working.

**Comment by pm4rcin** [comment]
I think it's how OSMand has it implemented (not entirely sure) in manifest: https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd/AndroidManifest.xml#L1130-L1140
But basically they have a silent notification which probably keeps it on foreground (take it with a big grain of salt) or notification is for other purposes.

**Comment by biodranik** [comment]
You're right. I've corrected the title. Thanks!

**Comment by qkqsb** [comment]
So is the root cause of this that location is not being obtained while the screen is off? I still do not see the option in settings to make location always available to the app.

**Comment by biodranik** [comment]
@qkqsb yes. See https://github.com/organicmaps/organicmaps/issues/2308

**Comment by IzzySoft** [comment]
I'm also one in need of this feature. Quoting from the linked issue:

> What is your use case when the device's screen is turned off/locked? Why do you need a location in that case? Probably, you need voice directions? Or maybe you want to avoid a delay in acquiring GPS location again when you reactivate the app?

All that, basically. For those here with the same needs, I found work-arounds for some of them:

* **avoid a delay in acquiring GPS location:** I'm running [Tower Collector](https://f-droid.org/de/packages/info.zamojski.soft.towercollector) in the background. So when I switch the screen back on, the current location is already available (and OM updates the screen accordingly within 1..2 seconds). Nice side effect: contributing to OpenCellID and MLS, for location services without GPS.
* **need voice directions:** not yet tested (just installed a few minutes ago for the next bike trip): [FakeStandby](https://f-droid.org/packages/android.jonas.fakestandby/) might help out if you have an OLED/AMOLED screen. This app simply switches all pixels off (black), which on OLED/AMOLED is said to be almost the same as switching the entire display off. It does that via a screen overlay, so apps "underneath" that will not notice the screen is off.

Both are just work-arounds and no real solutions, so it would be great to see OM implementing it properly. The way it currently is, for most use cases it does not really save battery (which the stated intention was) but rather impact UX in a negative way (no offense meant, just stating the obvious as seen by the other comments as well). Requesting the background location permission would be a start; it would still be up to the user to grant it. And if **not** granted, the current behavior would be fine – while **if granted** this indicates the user wants to keep navigation running "in background", including voice notifications (I wouldn't oppose an explicit setting, though – which if you prefer could even be initially off).

PS: My use-case also is biking – with the phone in the pocket and the earplugs in my ears for voice notifications. With those working, I'd only need to pull out the phone in confusing situations, like "turn right" when there are multiple ways to turn right (e.g. 3 or more streets/was meeting, or two streets/ways to the right with one shortly after the other). Today I had to pull out the phone much too often :see_no_evil:

**Comment by IzzySoft** [comment]
PPS: Tested for you: the variant with FakeStandby works fine as well. But as outlined is only useful if you have an OLED/AMOLED display (or a powerbank connected), as otherwise it probably will eat your battery quite fast due to consumed display power.

**Comment by Mike-0815** [comment]
Hello Alexander, hello to all other developers and to all others here :)

For me FakeStandby doesn't work, because I don't like to start/use FakeStandby while booting the phone (just before using OM I like to start it manually) and also it seems to be, that OM has to be in the foreground to do it's work and FakeStandby needs to be in the foreground to start it manually pushing the button.

Anyway it would be just a more-or-less bad turn-around solution of the problem.

I like OM REALLY VERY MUCH and it would be my first choice in several kind of outdoor-activities, but I am -STRONGLY- missing that funcionality, to use OM while screen is turned off, too !

I don't understand why this issue hasn't higher priority in developers mind, because it is essentially important to save battery-capacity while using any navigation app where there is no power-source available (cars, motor-bikes and so on) and with ANY GOOD Navigation-App it is enough, just to be guarded by voice-instruccions, in general NO display needed with those !

Also even very small (4 Megabyte) and simple GPS-Apps like 'GPS Compass Navigator' are able to navigate, while screen is powered off !

I really hope instantly, the developers ajust his minds, to higher priorize that issue, because I am sure, it would be useful/helpful to so many users out there, doesn't write here ...

Thanks for attention, kind regards,
Mike

**Comment by biodranik** [comment]
Hi @Mike-0815

1. You can notice references to the currently developed and tested background voice navigation https://github.com/organicmaps/organicmaps/pull/4611 _right above your comment_. It will be available soon.
2. Please notice how many open issues we have here on Github: almost 1800. If we do not implement something, then it means that we are busy with something else that is even more important. There are a few of us, and several active contributors, working in our free time, on a completely free app, for donations. If we had a lot of money, then many important issues, including this one, would have been fixed earlier.

**Comment by G-i-o** [comment]
Since Alexander mentioned it, I really like to take this opportunity to
express my gratitude to all those who work hard on or otherwise
contribute towards the development of OM.

Looking forward to see this requested feature to but also second and
understand what Alex mentioned. At any event, this app seems to have a
very solid and proactive development base, with additional many
contributors.

Great work, great app.

Thank YOU!

**Comment by IzzySoft** [comment]
@Mike-0815

> OM has to be in the foreground to do it's work and FakeStandby needs to be in the foreground to start it manually pushing the button.

The former is true, the latter not: you can start FakeStandby via QuickSettings. That's how I did it (see above), and it works. Admitted, it's a quirky work-around (getting rid of the overlay often takes more than one gesture here, but that might just be my devvice/ROM) – but it helps me stay patient until the OM developers have "navigation in background mode" ready (big thanks to the team from my side, too!)

**Comment by Mike-0815** [comment]
Thank you very much for your comments. Especially my thanks go to the developers, Alexander and others, who are now apparently working on the implementation of this functionality. I will follow the further development with great interest, thanks again for this great app !

**Comment by IzzySoft** [comment]
Yay! :star_struck:

**Comment by Phyks** [comment]
Hi,

I am experiencing this issue on iOS (same as https://github.com/organicmaps/organicmaps/issues/573#issuecomment-1372824273), as soon as the screen goes blank, the voice instructions would stop. This is very disappointing since I'm used to navigating by bike only with voice instructions, with the phone locked in my pocket. 

I understand from the referenced PR and commits that this has been fixed for iOS. The issue was therefore closed, but it was also missing from iOS and I do not see the corresponding PR/commits for iOS.

Is this supposed to have been solved for iOS as well?

Many thanks!
