### ISSUE TITLE
Do not translate similar languages for POIs/Place Page

### ISSUE THREAD

**Issue by matheusgomesms** [organicmaps/organicmaps#5817]
Currently, when a POI has a language different than the user’s (XX, for example), OM prioritizes English when there is the name:en tag and there is not the name:XX tag.

For example, when a Portuguese person is in Spain, OM displays in English on the map, and in English and Spain in the Place Page, IF there is not a name:pt tag.

However, Spanish is way more similar to Portuguese than English, which might confuse users who don’t speak neither English and Spanish.

Although this makes sense (prioritizing English), for similar languages perhaps it’s better to leave the original languages (let’s say Russian/Ukrainian, Norwegian/Danish/Swedish, Portuguese/Spanish/Catalan/French/Italian/Romanian, etc) than to translate to English.

One real example:
Spanish (original): Catedral de Santa María
English: Cathedral of Saint Mary
Portuguese: Catedral de Santa Maria

(in other words, here it’s exactly the same ES/PT, which is the majority of cases).

My suggestion here is to create some pairs of similar languages and don’t translate them to English (maybe only in the Place Page, if the user language is not available?).

**Comment by biodranik** [comment]
Modern systems have preferred languages list. If user selected pt,es and did not select en, then es should be displayed (if it's present in the data). If it doesn't work like that, then it's a bug that should be fixed.
If user does not have a language in his list, we can only fall back to en by default.

**Comment by matheusgomesms** [comment]
That’s true, OM should respect users preference OS language. However, I just tested here on iOS, and the error persists.

I removed English from my languages, and maintained Portuguese (main) and Spanish, only. POIs are still rendered in English primarily.

Examples checked:

1 - In Spain, names are mainly in the name tag, without name:es (some exceptions, of course). If the POI has name and name:en, name:en in prioritized.

2 - Outside Spain, let’s say Egypt, some POIs has name, name:ar, name:en and name:es. Name:en is prioritized above all.

Not sure how it works on Android, but it seems the logic of OM is to prioritize the OM setting language (and not from Operational System) and then English. It looks like OS settings are not used at all, at the moment.
