### ISSUE TITLE
Google and Valhalla cycling routes are more comfortable than OM

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#6027]
https://www.google.com/maps/dir/49.1424638,10.0679476/Mountain-Sports,+Johann-Sebastian-Bach-Platz+16,+91522+Ansbach/@49.1420774,10.0687402,17.27z/data=!3m1!5s0x4798bbccb44fc5d9:0x1f6090fe21324e9e!4m9!4m8!1m0!1m5!1m1!1s0x4798bbcd196d8851:0xd8d39080697dcd40!2m2!1d10.5738742!2d49.3023935!3e1?entry=ttu

https://www.openstreetmap.org/directions?engine=fossgis_valhalla_bicycle&route=49.1423%2C10.0680%3B49.3023%2C10.5738#map=10/49.1498/10.6059

**Comment by cayenne17** [comment]
Hello,
You can compare with Géovélo, which uses OSM data.
https://geovelo.app/fr/route/?from=10.067958%2C49.142446&to=10.573780%2C49.302300&e-bike=false&bike-type=own&c=10.392330%2C49.184422&z=10.25

**Comment by pabloscloud** [comment]
<img width="681" alt="Screenshot 2024-01-06 at 20 18 13" src="https://github.com/organicmaps/organicmaps/assets/93644977/a75a14e2-225a-4fe3-8180-ee59f0d8bfa9">
https://www.openstreetmap.org/#map=14/49.9375/9.1006

GraphHopper & Valhalla uses the much more safer track.

<img width="719" alt="Screenshot 2024-01-06 at 20 20 01" src="https://github.com/organicmaps/organicmaps/assets/93644977/d118f87d-3b9c-4c51-9cdf-e3f3f0529184">
This shows that the track is actually an official bicycle route.

Organic Maps (and  OSRM) still routes using the ST nearby where cars and other vehicles are allowed to drive 100km/h there. It's much nicer and doesn't take too much longer (if at all) to use the track instead. Most cyclists drive there instead and only a few use the ST where they get honked at (by me as well lol) and get overtaken way too close more often than not (not by me but seen by me).

I'd request to check the speed before navigating the router over those street with such high speeds. Could also be a toggle in the App, so users could disable it (tho I see no point in disabling this for bikers)

Thanks for considering.

**Comment by biodranik** [comment]
@pabloscloud please share the exact link to starting and ending points on osm.org to compare. Did you check if all tags including route type and max speed are correct?

OM chooses the fastest speed route.

**Comment by pabloscloud** [comment]
I think I got this fixed by adding some more information to OSM so that organic maps routes better but I'll check again tonight.

**Comment by pabloscloud** [comment]
Yes, this is fixed.

https://omaps.app/o4D4VM5TdL/Abandoned_Railway

![Screenshot_20240319-062126](https://github.com/organicmaps/organicmaps/assets/93644977/ec462fb7-fabf-4144-baf8-92fcbf3c54f6)

**Comment by Konfekt** [comment]
Hello,

This route is still not fixed; I wonder why Graphopper prefers this detour to the North; the destination lies in the sout.

![image](https://github.com/user-attachments/assets/61b0c323-1bb6-4a34-9fb3-1126edf7eb26)

This is Valhalla's path:

![image](https://github.com/user-attachments/assets/f3080bf2-d575-436c-a0a5-4c9c203a21b5)

https://www.openstreetmap.org/directions?engine=graphhopper_foot&route=52.26060%2C10.52700%3B52.23235%2C10.38751#map=13/52.24672/10.45667

**Comment by pastk** [comment]
> https://www.openstreetmap.org/directions?engine=fossgis_valhalla_bicycle&route=49.1423%2C10.0680%3B49.3023%2C10.5738#map=10/49.1498/10.6059

Why OM route is inferior? Its hard to tell without more details.

![image](https://github.com/user-attachments/assets/30fc4adf-0d53-4a4c-923b-05c3aa511562)

Valhalla routes through some tracks (of undefined quality) and small service roads, while OM stays (and route length is similar).

BTW OSRM suggests the same or very similar route https://www.openstreetmap.org/directions?engine=fossgis_osrm_bike&route=49.14230%2C10.06800%3B49.30230%2C10.57380#map=11/49.2187/10.3210&layers=Y
