### ISSUE TITLE
Intermittent performance problem

### ISSUE THREAD

**Issue by fizwidget** [organicmaps/organicmaps#6085]
**Describe the issue**
Since upgrading to iOS 17 a few days ago, I’ve noticed an intermittent performance problem in Organic Maps. Normally panning around the map is silky smooth, but sometimes it’ll get into a state where the framerate is noticeably lower. Inertial scrolling also works less reliably when this happens (sometimes the map stops moving immediately after I lift my finger). 

Killing and re-launching the app resolves the problem (until it reappears later on). 

**Steps to reproduce**
Unsure - I haven’t noticed a pattern to it yet. 

**Expected behavior**
Performance should consistently be good without the need to kill & relaunch the app. 

**Screenshots**
None yet, I might try and capture a screen recording next time it happens though. 

**System information:**
 - Operating system and its version: iOS 17.0
 - Organic Maps version: ⁦2023.09.01-5⁩
 - Device Model: iPhone Xs Max

**Additional context**
I suspect it’s related to my iOS 16 -> 17 upgrade, but don’t have any proof. That’s the only thing I can think of that changed recently.

**Comment by biodranik** [comment]
Did you try to compare it with the app store version? Could it be something that we changed recently?

Note: if you downloaded some newer maps in a beta version, it's better to delete them before downgrading the app, as we don't guarantee forward compatibility. And it's safer to always backup your bookmarks.

**Comment by fizwidget** [comment]
Oh I’m using the App Store version. Never tried a beta release.

**Comment by biodranik** [comment]
Sorry, I see ) Forgot that we published a hot-fix for the iOS 🤦‍♂️

Was you able to reproduce the issue again after a reboot?

**Comment by fizwidget** [comment]
I’ve not tried a full reboot yet. Will do so now though 👍

**Comment by fizwidget** [comment]
@biodranik I rebooted my phone last night but the problem is back again this morning. So rebooting seems to be a temporary fix, similar to killing & relaunching the app.

I got some screen recordings this time though! The first video demonstrates the problem and the second shows normal performance after killing & relaunching the app. It's hard to see the framerate difference in the videos - it's certainly more noticeable in person. The inertial scrolling problem is clearly visible though (note how panning is "jerky" in the first video but not in the second).

- [Performance problem](https://drive.google.com/file/d/1DPDVbinv1rC9gBQKn2QVJ11dLVaU-1aW/view?usp=share_link)
- [Back to normal](https://drive.google.com/file/d/1iOi9xeKdBr7DxK-c1EHDfnpE_9SmceTn/view?usp=share_link)

**Comment by fizwidget** [comment]
I’ve been experimenting with `?debug-info` a bit today. When the problem occurs the framerate halves to ~30 FPS, whereas normally it’s ~60 FPS (during panning). 

Interesting how the framerate literally halves. Almost feels like the OS might be throttling how frequently a timer is firing? (Random guess!)

A couple of other tidbits:
* The problem occurs at least once a day for me, usually the first time I open Organic Maps that day. 
* Upgrading to iOS 17.0.1 and OM ⁦2023.09.22-20⁩ hasn’t changed anything.

**Comment by biodranik** [comment]
How old is your battery? Do you have throttling enabled? https://www.itpro.com/mobile/battery-life/356946/how-to-turn-off-battery-throttling-on-iphone

**Comment by fizwidget** [comment]
Battery is only 11 months old and throttling isn’t enabled. So probably something else going on. 

![IMG_0639](https://github.com/organicmaps/organicmaps/assets/1172012/8536de07-1384-4641-81d6-7fe04e9e558b)

**Comment by biodranik** [comment]
It could be some styles/rendering bug in our engine. Did you check if the issue happens over some specific map areas?

**Comment by fizwidget** [comment]
I’ve just tried a few different map areas - framerate stayed at 30FPS regardless of the area being viewed. This was across multiple cities in different continents, remote desert areas, and the middle of the ocean. 

(All of them render at 60FPS after killing & relaunching.)

**Comment by biodranik** [comment]
@pastk could it be related to https://github.com/organicmaps/organicmaps/issues/6158 ?

**Comment by pastk** [comment]
> @pastk could it be related to #6158 ?

Those changes haven't been released yet..

**Comment by mikossheev** [comment]
Same here, commented in the other issue as well. I’m open to help in any way, just let me know.
https://github.com/organicmaps/organicmaps/issues/6160#issuecomment-1761392232

**Comment by fizwidget** [comment]
This problem seems _partially_ fixed with the latest release. The framerate drops still occur, but inertial scrolling now functions normally while the app is in this state. I remember seeing something about inertial scrolling in the release notes - I guess we have that fix to thank? 🎉

Here’s the low-framerate state with the latest release (it’s happened several times already for me):

![IMG_1992](https://github.com/organicmaps/organicmaps/assets/1172012/c814d427-06f3-4a26-82b8-517eb9a4bfce)

As usual, killing & re-launching gets the framerate back up to 60:
 
![IMG_1993](https://github.com/organicmaps/organicmaps/assets/1172012/e84cbd08-a60f-45a3-be7f-24db0579138f)

**Comment by Jean-BaptisteC** [comment]
@fizwidget any news about performance?

**Comment by fizwidget** [comment]
@Jean-BaptisteC no changes. At least once a day it gets stuck at 30FPS, and I have to kill & relaunch to get it back to 60. 

It seems to occur pretty reliably in the morning (the first time I use OM for the day).

**Comment by biodranik** [comment]
Any hints on how to reliably reproduce the issue are appreciated...

**Comment by fizwidget** [comment]
Yep, I’ll post here if I figure something reliable out. So far though the only hint is that it seems to occur randomly after OM has been running for a while (not sure if that’s the right terminology). 

If I manually kill OM (or reboot my phone), the problem _never_ happens when I subsequently launch OM. Always 60FPS in this scenario. Later that day or the next morning though…30FPS again 🥲

I’ve tried tapping through all the UI options, calculating routes, zooming/panning, etc. None of these interactions trigger the problem (at least, not immediately).

**Comment by biodranik** [comment]
May be it is caused by something that you (or the system) do after moving OM into the background.

**Comment by fizwidget** [comment]
Just noting that I upgraded to an iPhone 16e recently and this problem still happens with it.

I’d wondered if it might only affect old/slow phones (like my previous XS Max), but seems that’s not the case.

**Comment by biodranik** [comment]
So the issue happens _always_ after OM was in the background for some time, right?

**Comment by mikossheev** [comment]
@biodranik Yes! Always after the periods of long background state.
@fizwidget Its not only on old phones. I had this issue on 13 Pro, and now I am having it on 16 Pro Max as well.

**Comment by biodranik** [comment]
It's likely a bug in our rendering engine. It would be great to enable logs in OM settings, and share them with us when you reproduce issue via Report a bug.

**Comment by mikossheev** [comment]
@biodranik Just got the issue reproduced and reported via the app with logs enabled! Hope it helps!
