### ISSUE TITLE
Issue when selecting "Spanish" language

### ISSUE THREAD

**Issue by robertoprubio** [organicmaps/organicmaps#6289]
**Describe the issue**
"Spanish" language cannot be selected at voice spech languages. When "Spanish" is clicked "Spanish from Mexico" is selected
and the navigation voice is "Spanish from Mexico"

**Steps to reproduce**
1. Go to Settings
2. Go to Voice instructions
3. Select "Spanish" at Voice Language
4. Enter again at the Voice Language selector then "Spanish from Mexico" is selected and also the navigation voice is "Spanish from Mexico"

**Expected behavior**
"Spanish" (from Spain) is really selected instead of "Spanish from Mexico" when "Spanish" is selected.

**System information:**
 - Android 13
 - 2023.09.22-27-android but also occurs in prev versions
 - Device Model: Pixel 7 Pro

**Comment by sandy99405** [comment]
@Jean-BaptisteC   @biodranik 

Recording :

https://github.com/organicmaps/organicmaps/assets/55664068/20c16769-e68a-4ec5-a7ee-e38a18e1b5f7

please check the commit for the related change of code : 

[commit done] :  https://github.com/organicmaps/organicmaps/commit/7755507cfbf83f1e5a40d91623d17edd56f3d140

**Comment by biodranik** [comment]
Thanks! Did you test it? Do you hear the difference between different selected languages when you press the Test button? Please also fix pt and pt-BR, and test the voice (app_tip_00 string is different for Portuguese and Brasil variants).

P.S. I forgot about this issue and created a duplicate #6756

**Comment by sandy99405** [comment]
@biodranik  Yes I did test it and they are different. But I couldn't make a pull reuest with it so it got included in the  [Android] Added Search Privacy #6515 PR. I will also look into pt and pt-BR as you mentioned👍

**Comment by sandy99405** [comment]
@biodranik  @Jean-BaptisteC  although the app_tip_00 string is different for Portuguese and Brasil variants, they are saying the same thing with different accents of english i.e, (Thank you for using our community-built maps!)  Portugal accent and Brazil acccent.

**Comment by biodranik** [comment]
If the user selected pt, then the Portuguese test string should be heard, if the user selected pt-BR, then the Brazil test string should be heard. It's easy to test because they are different:
```
    pt = Obrigado por utilizares os nossos mapas construídos pela comunidade!
    pt-BR = Obrigado por você usar nossos mapas criados pela comunidade!
```

You can also temporarily add an es-MX string that will be different from es string into sounds.txt (and regenerate strings using tools/unix/generate_localization.sh) to test Spanish too.

**Comment by biodranik** [comment]
It's a bug that should be fixed. Voices are speaking an English string instead of pt or pt-BR.
Do other languages work?

If this bug was introduced by your change, then please fix it here. If it also reproduces on the master branch and is not related to your changes, please create an issue and make a separate fix for it.

**Comment by sandy99405** [comment]
@biodranik  The bug is already in the master branch, it wasn't introduced by my changes. But I will resolve the bug after amending the previous commit.

**Comment by robertoprubio** [comment]
The issue still persists in current beta and last stable versions

**Comment by biodranik** [comment]
@robertoprubio the fix is not released yet. Will be available in the next update.

Fixed by https://github.com/organicmaps/organicmaps/pull/6934
