### ISSUE TITLE
CarPlay not showing exit information

### ISSUE THREAD

**Issue by dvdmrtnz** [organicmaps/organicmaps#6599]
* Related to https://github.com/organicmaps/organicmaps/issues/5111

When routing with the app, it seems that the exit information is not shown until it is less than 1.8km away. However in CarPlay it doesn't show any information the whole time. See images:

2km away:
<img src="https://github.com/organicmaps/organicmaps/assets/47610359/360e951d-7971-483d-9834-66d2dc217277" width="320"> <img src="https://github.com/organicmaps/organicmaps/assets/47610359/5556ba15-9cba-4fd7-b525-af16d471dde6" width="400"/>

1.8km away:
<img src="https://github.com/organicmaps/organicmaps/assets/47610359/7265af0d-579b-4158-a68c-e5a239faf7ad" width="320"/> <img src="https://github.com/organicmaps/organicmaps/assets/47610359/13403072-d851-4bbb-a99e-35ae2b621902" width="400"/>

100m away:
<img src="https://github.com/organicmaps/organicmaps/assets/47610359/f7ae384f-340a-45e2-b9da-3bd0afa4fda9" width="320"/> <img src="https://github.com/organicmaps/organicmaps/assets/47610359/b7505a19-77b7-4257-9fdd-4a2dd0cbac7d" width="400"/>

However if I start the navigation less than 1.8km away, CarPlay does show exit information:
<img src="https://github.com/organicmaps/organicmaps/assets/47610359/7c67acf2-04aa-4bcd-a6ba-94aef7f45b09" width="400"/>

**Comment by dvdmrtnz** [comment]
Location is here:

42.792288, -1.678533
https://omaps.app/wn_Ty9B5cZ/88
om://wn_Ty9B5cZ/88

And here is gpx if someone wants to simulate this route:

[gpx-a15-exit88.gpx.zip](https://github.com/organicmaps/organicmaps/files/13400283/gpx-a15-exit88.gpx.zip)

**Comment by biodranik** [comment]
@AntonM030481 can you please take a look?

**Comment by biodranik** [comment]
Should be also fixed by #7711, @dvdmrtnz was it easy to reproduce?

**Comment by dvdmrtnz** [comment]
This is only partially fixed. Now the distance to the exit is shown. However, the exit information is still missing.

<img src="https://github.com/organicmaps/organicmaps/assets/47610359/c2eec456-fdd4-4c4c-9669-50b833cce26f" width="400"/>


<img src="https://github.com/organicmaps/organicmaps/assets/47610359/2daf953d-ff6f-43ee-9328-7aa6e1f80c3e" width="400"/>
