### ISSUE TITLE
Phone Screen Not Staying On (Screen Automatically Turns Off and Requires Lock Screen Password)

### ISSUE THREAD

**Issue by DesertBear** [organicmaps/organicmaps#6921]
**Describe the issue:**
I use Organic Maps for cycling.  I create routes using the [bikerouter.de verylowtraffic profile](https://bikerouter.de/#map=7/51.75300/-1.27000/standard&profile=fastbike-verylowtraffic) and then import the GPX files into Organic Maps to follow along.  I never have any active navigation enabled, I just use the Organic Maps follow-along-mode to follow the blue GPX overlays on the screen.

Since the latest Organic Maps update, the screen doesn't stay on any more.  The screen keeps automatically turning off and requires the lock screen password to be entered every time.

This is a PITA when cycling, as it means it's necessary to keep turning the phone back on every few minutes and entering the lock screen password.  Entering the lock screen password with gloves on, on a bike that's continuously jumping around, is a real headache – riders should really stop the bike as it's dangerous, however stopping the bike every few minutes is also not very practical.

**Steps to reproduce:**
1) Open a pre-planned route GPX file in Organic Maps [Android File Explorer > Open With > Organic Maps].

2) Click the blue location arrow so that the screen orientates to the direction of travel, instead of north.

3) Start cycling.

**Actual behaviour:**
1) After a few minutes cycling, the screen goes black.

2) Pressing the phone power button displays the Android lock screen and requires entering the lock screen password.

3) Go to 1.

**Expected behaviour (how it worked in the 2023.11.17-17-android previous version):**
1) With the Organic Map settings set as listed below, the screen should stay on, so that the rider can follow the GPX route on the map.

2) Pressing the phone power button should turn the display off.  Pressing the phone power button again should turn the display back on and display Organic Maps again without entering a lock screen password.  Trying to go to another application (for example by using the Android app switcher), should prompt for the lock screen password.

**Android Settings:**

| Setting                  | Status        |
| -------------            | ------------- |
| Screen timeout           | After 5 minutes of inactivity    |

**Organic Maps Settings:**

| Setting                  | Status        |
| -------------            | ------------- |
| Power saving mode        | Never    |
| Keep the screen on       | Enabled  |
| Show on the lock screen  | Enabled  |

![Screenshot](https://github.com/organicmaps/organicmaps/assets/27423064/5e79a0e8-d154-4376-ad90-47b62a386c08)

**Versions:**
| Name                       | Version        |
| -------------              | -------------  |
| Organic Maps               | 2023.12.18-12-Google   |
| Operating System           | Android 11  |
| Google Play System Update  | 1 November 2023 |
| Device                     | Nokia 3.2 (Android One) |

**Comment by biodranik** [comment]
@rtsisyk the screen should not be turned off if the position is centered. Many cyclists, walkers and drivers are using OM in this way. Isn't it already fixed by @pastk in https://github.com/organicmaps/organicmaps/pull/6674 ?

**Comment by biodranik** [comment]
@DesertBear there is a bug in OM: the map screen doesn't dim until you lock the device or open any other dialog and then return back to the map screen. It should work in the beta, you can install it from here: https://t.me/OrganicMapsApp/278

**Comment by vng** [comment]
Fixed here https://github.com/organicmaps/organicmaps/issues/6921

Of course, "Keep screen on" should be enabled.

**Comment by DesertBear** [comment]
> @DesertBear there is a bug in OM: the map screen doesn't dim until you lock the device or open any other dialog and then return back to the map screen.

> 2023.12.19-15-Google-beta.apk
> Respect the 'Keep the screen on' setting regardless of current location mode

> Also fixes some bugs introduced in #6053
> 
> 1. have the setting ON, location current and map centered  - the screen will stay on
> 
> * switch to some other app
> * switch back to OM, the screen will go to sleep after some time (in case there was no location mode change)






I think that's likely where the issue lies.  When bike touring/bikepacking it's not uncommon that I have a bike computer running as well, so I may have switched to that app at some point to make sure it was on.  I.E.

![Untitled](https://github.com/organicmaps/organicmaps/assets/27423064/2da6d8e7-dd1a-4653-a1d5-485a5cbd8f3d)



What's odd though, is about an hour into the journey I was starting to get frustrated with it, so I stopped to check that the settings were correct.  Then, I'm pretty sure I exited all apps and started again with only Organic Maps running and it continued to automatically turn the screen off.  Perhaps I though I exited Organic Maps as well, but didn't – or maybe I used the power button.  I don't know.  I don't think I'll be back on the bike to try it again until after Christmas.

**Comment by pastk** [comment]
In the November release the keep screen on setting was buggy meaning it was actually working as expected only after some non-obvious manipulations in the app. That should be fixed in the current December release (just out). Happy cycling, happy X-mas and don't hesitate to ping here if something doesn't work still!

**Comment by pastk** [comment]
In the November release the keep screen on setting was buggy meaning it was actually working as expected only after some non-obvious manipulations in the app. That should be fixed in the current December release (just out). Happy cycling, happy X-mas and don't hesitate to ping here if something doesn't work still!

**Comment by biodranik** [comment]
@pastk no, this fix is not included in the December release.

**Comment by DesertBear** [comment]
@biodranik 

Indeed, this issue still occurs in Organic Maps "2023.12.21-1-Google".

**Comment by pastk** [comment]
@DesertBear right, sorry for the confusion.

The fix was included in the latest 23121915 beta.
You can join beta via a link in the bottom of https://organicmaps.app/ or download it from the TG channel https://t.me/OrganicMapsApp/277
